### ISSUE TITLE
incomplete instructions for running sample server

### ISSUE THREAD

**Issue by thomasmckay** [grafeas/grafeas#107]
https://github.com/grafeas/grafeas/blob/master/samples/server/go-server/api/server/README.md

As a new comer to the project, this file lacks enough detailed instructions to run sample server. For me, after adding src to $GOPATH I get this on centos7

```
$ go run main.go -config config.yaml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fa83a]

goroutine 1 [running]:
github.com/grafeas/grafeas/samples/server/go-server/api/server/api.Run(0x0, 0xc42011ff68)
	/home/vagrant/go/src/github.com/grafeas/grafeas/samples/server/go-server/api/server/api/api.go:48 +0x3a
main.main()
	/home/vagrant/code/grafeas/samples/server/go-server/api/server/main/main.go:38 +0xa4
exit status 2
```

**Comment by thomasmckay** [comment]
Update: It is the _-config config.yaml_ that is SEGVing

**Comment by furuholm** [comment]
Thanks for reporting this issue.

In investigating this issue I actually found several things that needs to be corrected. But lets first look at the issue you are having.

The config file in the main directory was added by mistake by me. Instead use the config file in the root directory called `config.yaml.sample`. Unfortunately this file also contains an issue as a tab character had snuck in on row 25 (the line containing `# - "http://example.net`). Either remove the tab char or the complete line. Hopefully this should solve the issue you are having.

Here is the list of issues I found that needs to be corrected:
- [ ] `samples/server/go-server/api/server/main/config.yaml` was added by mistake and needs to be removed.
- [ ] `config.yaml.sample` contains invalid tab character.
- [ ] [samples/server/go-server/api/server/README.md](https://github.com/grafeas/grafeas/blob/master/samples/server/go-server/api/server/README.md) overlaps [docs/running_grafeas.md](https://github.com/grafeas/grafeas/blob/master/docs/running_grafeas.md) 
- [ ] [samples/server/go-server/api/server/README.md](https://github.com/grafeas/grafeas/blob/master/samples/server/go-server/api/server/README.md)  states that `Storage: map backed in memory server storage`. This is not correct as PostgreSQL is now supported.

Also: maybe we should consider checking the config for `nil` values. The problem that caused the issue reported herein was due to the api config not being present in the config file.

**Comment by thomasmckay** [comment]
About my setup, which likely influences the following notes:
clair - master
klar - to scan images against clair
grafeas - master

I am unable to find any data from clair in psql tables. curl'ing grafeas shows proper results afaict (lots of CVE notes). Is the storage_type being honored? _storage_type: "postgres"_

Note I'm very new to _go_ so errors could certainly be self-inflicted.
Thanks for help!

**Comment by thomasmckay** [comment]
updated above note w/ proper clair branch

**Comment by thomasmckay** [comment]
It was using memcache. Switching to using the config.yaml.example in home dir and changing to postgres does now tries to use postgres. Clair errors creating project; I'll debug. I'm using postgres-9.6.

**Comment by thomasmckay** [comment]
I'm unsure why, but changing grafeas config.yaml from _host: "127.0.0.1:5432"_ to _host: "localhost:5432"_ allows the the clair-to-grafeas connection to work. (I haven't been able to get the _delve_ go debugger to work to find out more details.)

Thanks again for all the help!

**Comment by furuholm** [comment]
Good to hear that you got things working! I've created PR #108 to address the issues I listed above.

I suggest you close this issue if you feel that your problem has been resolved.

**Comment by R2wenD2** [comment]
@thomasmckay are you still having issues? Can this be closed?

**Comment by aysylu** [comment]
Closing this due to inactivity for 6+ months, and it appears to be resolved.
